"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Eye, Loader2, RefreshCw, Users } from "lucide-react";

type Report = { daily:{ day:string; views:number; uniques:number }[]; pages:{ path:string; views:number; uniques:number }[]; totals:{ views:number; uniques:number } };
function Stat({ label, value, icon:Icon }:{ label:string; value:number; icon:typeof Eye }) { return <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><Icon size={17} className="text-orange-500"/><p className="mt-5 text-3xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-xs text-[var(--muted)]">{label}</p></div>; }
export default function TrafficPage() {
  const [report, setReport] = useState<Report|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [days,setDays]=useState(30);
  const load = useCallback(async () => { setLoading(true); setError(""); const r=await fetch(`/api/admin/analytics?days=${days}`); if(r.status===401) return location.assign("/admin/login"); const body=await r.json().catch(()=>({})); if(!r.ok) setError(body.error ?? "Could not load traffic."); else setReport(body); setLoading(false); }, [days]);
  useEffect(()=>{ void load(); },[load]);
  const max = useMemo(()=>Math.max(1,...(report?.daily.map(d=>d.views) ?? [1])),[report]);
  return <div className="mx-auto max-w-6xl p-6 md:p-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-orange-500">Insights</p><h1 className="mt-2 text-3xl font-semibold">Traffic</h1><p className="mt-2 text-sm text-[var(--muted)]">First-party page views with anonymous, daily session deduplication. No IP address or browser fingerprint is stored.</p></div><div className="flex gap-2"><select value={days} onChange={e=>setDays(Number(e.target.value))} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm"><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select><button onClick={()=>void load()} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-2.5"><RefreshCw size={15}/></button></div></div>
  {loading ? <div className="flex items-center gap-2 py-20 text-sm text-[var(--muted)]"><Loader2 className="animate-spin" size={16}/> Loading analytics…</div> : error ? <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-5 text-sm text-amber-600">{error}</div> : report && <><div className="grid gap-4 md:grid-cols-3"><Stat label="Page views" value={report.totals.views} icon={Eye}/><Stat label="Unique page sessions" value={report.totals.uniques} icon={Users}/><Stat label="Tracked pages" value={report.pages.length} icon={Activity}/></div>
  <div className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-sm font-semibold">Daily views</h2><div className="mt-6 flex h-44 items-end gap-1">{report.daily.map(d=><div key={d.day} className="group relative flex h-full flex-1 items-end"><div className="w-full min-h-1 rounded-t bg-orange-500/70 transition hover:bg-orange-500" style={{height:`${Math.max(3,d.views/max*100)}%`}}/><span className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-black px-2 py-1 text-[10px] text-white group-hover:block">{d.day}: {d.views}</span></div>)}</div></div>
  <div className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-sm font-semibold">Top pages</h2><div className="mt-4 divide-y divide-[var(--border)]">{report.pages.length ? report.pages.map(p=><div key={p.path} className="flex items-center gap-4 py-3 text-sm"><span className="flex-1 font-medium">{p.path}</span><span className="text-[var(--muted)]">{p.uniques} unique</span><span className="w-16 text-right font-semibold tabular-nums">{p.views} views</span></div>) : <p className="py-8 text-center text-sm text-[var(--muted)]">Traffic will appear after the content table is set up and visitors browse the site.</p>}</div></div></>}
  </div>;
}
