import type { ExperienceContent, ProjectContent } from "./types";

export const DEFAULT_PROJECTS: ProjectContent[] = [
  {
    id:"bb8-rag", kind:"project", title:"BB8 Co-Pilot x Tech Portfolio",
    technicalDetails:[{label:"Retrieval architecture",detail:"Section-aware source chunks → text-embedding-3-small (1,024 dimensions) → Amazon S3 Vectors. Hybrid ranking places up to two lexical matches before distance-qualified semantic evidence, then deduplicates and applies a bounded context budget."},{label:"Grounded generation & evaluation",detail:"OpenAI Responses generates from retrieved sources with page citations and constrained navigation/contact tools. Keyword fallback preserves service when semantic search fails; fixed 4 / 0.65 remains the baseline. Separate development/held-out suites compare evidence coverage, refusal and answer grounding."},{label:"Serving & observability",detail:"Next.js SSR on Amplify; DynamoDB-backed content, signed admin sessions, per-purpose analytics and request/token telemetry. Budgeted evaluation is separate from reindexing and never persists visitor conversations."}],
    evaluation:[{metric:"Legacy offline evidence Hit@3",value:"83/83",context:"Frozen 83-question lexical regression, September 2026. ANY expected route plus ALL required evidence fragments; not generated-answer accuracy.",source:"https://github.com/Skywalker1910/Tech-Portfolio/blob/rag-evaluation/docs/RAG_EVALUATION_RESULTS.md"},{metric:"Live held-out hybrid evidence hit",value:"5/8 at K=4; 6/8 at K=6 or 8",context:"56-chunk production snapshot; eight answerable questions. Four ambiguous/absent-fact cases are excluded from this positive-hit denominator. Not evidence of improved answer quality.",source:"https://github.com/Skywalker1910/Tech-Portfolio/blob/rag-evaluation/docs/RAG_EVALUATION_RESULTS.md"}],
    limitations:["Small, domain-specific evaluation; lexical fragments can pass without a complete or factually correct generated answer.","Adaptive retrieval remains experimental. A higher chunk limit changes evidence per request, not knowledge in the corpus."],
    blurb:"A live, source-grounded portfolio assistant that retrieves verified evidence before answering visitors.",
    description:"Built the AI co-pilot for this portfolio with OpenAI Responses and Embeddings, Amazon S3 Vectors, and a persistent Next.js chat overlay. BB-8 retrieves only relevant, verified portfolio evidence, cites the matching pages, supports navigation and contact workflows, and falls back to deterministic local retrieval when vector search is unavailable.",
    highlights:["Designed section-aware chunking and retrieval over a verified knowledge corpus","Implemented OpenAI embeddings with Amazon S3 Vectors semantic search","Added grounded answers, source links, page navigation, resume delivery, and contact-form drafting","Built retrieval evaluation, usage telemetry, and privacy-aware first-party analytics","Deployed the SSR application through AWS Amplify with DynamoDB-backed content and administration"],
    tags:["LLM","RAG","OpenAI API","Embeddings","Amazon S3 Vectors","Next.js","TypeScript","React","AWS"],
    year:2026, status:"in-progress", featured:true, published:true, sortOrder:0,
    github:"https://github.com/Skywalker1910/Tech-Portfolio", demo:"https://www.adityamore.dev"
  },
  {
    id:"neurallog", kind:"project", title:"Neural Log — Personal Activity & Progress System",
    technicalDetails:[{label:"Data & analytical model",detail:"Structured training sets, nutrition, study sessions and habits feed SQL aggregations, streaks, personal records and calendar heatmaps. Eight evidence-based attributes use auditable XP transactions; missing observations are not silently treated as completed or failed activity."},{label:"AI integration",detail:"Private AI weekly reviews summarize recorded activity into strengths, opportunities and contextual charts. This is an LLM-assisted product feature, not a trained activity-prediction model."},{label:"Persistence & delivery",detail:"Session-authenticated Flask APIs serve a React/TypeScript SPA from one origin. SQLite and versioned SQL migrations manage relational records; per-user JSON/JSONL stores flexible checklist definitions and submissions. Docker/Gunicorn/Caddy run on Lightsail."}],
    limitations:["No predictive-model accuracy or causal improvement benchmark is reported; XP/streaks measure recorded activity, not health or productivity outcomes.","Public capture shows sign-in only. Authenticated dashboards are intentionally excluded to avoid exposing personal activity."],
    blurb:"A live multi-workspace tracker with an auditable XP ledger, analytics, AI weekly reviews, and long-term progress tools.",
    description:"Built a production activity system for training, nutrition, learning, habits, and daily routines. Flask serves a React and TypeScript application from one origin, SQLite is the authoritative store, and Docker Compose with Caddy runs the service on AWS Lightsail.",
    highlights:["Created eight evidence-based attributes backed by an auditable XP transaction ledger","Built training, nutrition, learning, habits, goals, streaks, records, and calendar analytics","Added private AI weekly reviews, illustrated personal libraries, and accessibility-focused mobile workflows","Implemented admin-managed invite codes, isolated administration, privacy-aware leaderboards, SQL migrations, and verified backups","Deployed Flask/Gunicorn, React, SQLite, Docker Compose, and Caddy on AWS Lightsail"],
    tags:["Python","Flask","React","TypeScript","SQLite","Docker","AWS","Data Analysis"],
    year:2026, status:"in-progress", featured:true, published:true, sortOrder:1,
    github:"https://github.com/Skywalker1910/Neural-Log", demo:"https://neurallog.adityamore.dev"
  },
  {
    id:"movie-recommendation", kind:"project", title:"Movie Recommendation Engine",
    technicalDetails:[{label:"Dataset & leakage control",detail:"Joined MovieLens ratings to TMDB/IMDb metadata through movie identifiers. A 45,433-title feature catalog and 26,024,289 ratings use chronological partitions: 20,720,316 before 2015 for training, 1,913,720 from 2015 for validation and 3,390,253 from 2016 onward for testing."},{label:"Models & cold-start",detail:"TF-IDF cosine similarity uses plot, genres, director, cast and keywords. Biased FunkSVD models rating offsets; NeuMF combines generalized matrix factorization with an MLP over user/item embeddings. Content and Bayesian popularity provide fallback signals for sparse/new users."},{label:"Experiment & serving separation",detail:"Nine notebooks cover EDA, preprocessing, memory-based CF, factorization, neural models and hybrid validation. Flask serves serialized/Hugging Face artifacts with lazy loading; React uses live TMDB enrichment. Versioned diagnostics and CI/CD validate and ship the Docker deployment on EC2."}],
    evaluation:[{metric:"FunkSVD RMSE / MAE",value:"0.7600 / 0.5627",context:"30-epoch notebook experiment on 200 qualifying users with substantial histories. Roughly 21% lower RMSE than user-mean SVD (0.9582); not a universal-user result.",source:"https://github.com/Skywalker1910/Movies-Recommendation-Engine/blob/main/documents/README.md"},{metric:"Ranking NDCG@10 / Hit@10",value:"SVD: 0.1123 / 0.4975; FunkSVD: 0.0851 / 0.3970",context:"Shared notebook ranking protocol. Better rating RMSE did not imply better top-K ranking.",source:"https://github.com/Skywalker1910/Movies-Recommendation-Engine/blob/main/documents/07_matrix_factorization.md"},{metric:"TF-IDF Precision@10",value:"0.699",context:"Genre-overlap proxy on 100 seed movies, not human relevance judgments. Quality reranking scored 0.680 on the same proxy.",source:"https://github.com/Skywalker1910/Movies-Recommendation-Engine/blob/main/documents/05_content_based.md"},{metric:"NeuMF v2 validation RMSE / MAE",value:"0.8543 / 0.6452",context:"Later retraining report, approximately 13M parameters. Distinct experiment from the notebook's original NeuMF result (1.0725 RMSE); not asserted to be a live-serving measurement.",source:"https://github.com/Skywalker1910/Movies-Recommendation-Engine/blob/main/scripts/RETRAINING_ANALYSIS.md"}],
    limitations:["Most comparisons are validation-based, and the qualifying-user filter excludes cold-start/light users.","Hybrid validation uses a different sample, so its RMSE is not directly comparable to the 200-user benchmark. Production model/checkpoint availability must be checked separately.","RMSE does not establish ranking quality, novelty, diversity or fairness."],
    blurb:"A live hybrid recommender spanning reproducible ML experiments, a Flask API, a React client, and AWS deployment.",
    description:"Expanded a Clemson course project into a production application combining FunkSVD, NeuMF, TF-IDF content similarity, and Bayesian popularity over MovieLens, TMDB, and IMDb data. The system includes personalized onboarding, watch history, live TMDB enrichment, Hugging Face model artifacts, an isolated admin dashboard, and automated CI/CD to AWS EC2.",
    highlights:["Processed 26M+ ratings across 270K users and 45K movies","Achieved RMSE 0.7600 with FunkSVD, about 21% better than the baseline","Improved NeuMF validation RMSE from 1.0725 to 0.8543 while reducing parameters from 26.3M to 13.1M","Combined collaborative, neural, content, and popularity signals for coverage-aware ranking","Moved versioned model artifacts to Hugging Face with automatic download when absent","Deployed Flask, React, Docker, nginx, gunicorn, SSL, and GitHub Actions on AWS EC2"],
    tags:["Python","scikit-learn","PyTorch","Flask","React","SQLite","Docker","AWS","Hugging Face","Recommender Systems"],
    year:2024, status:"completed", featured:true, published:true, sortOrder:2,
    github:"https://github.com/Skywalker1910/Movies-Recommendation-Engine", demo:"https://movies.adityamore.dev", huggingface:"https://huggingface.co/Skywalker1910/movie-rec-models"
  },
  {
    id:"bb8-transformer", kind:"project", title:"BB-8: Transformer Language Model",
    technicalDetails:[{label:"Transformer from first principles",detail:"PyTorch decoder-only models implement learned token/position embeddings, causal multi-head self-attention, Pre-LN blocks and tied language-model heads. Character and BPE tokenizers support separate training/evaluation loops and greedy, temperature, top-K and nucleus decoding."},{label:"Fine-tuning & reproducibility",detail:"Qwen2.5-0.5B/Instruct LoRA studies use assistant-only supervision, pinned model revisions, dataset hashes and versioned experiment registries. A 192/48-example evidence-only pilot trained 540,672 adapter parameters; its outputs were tested separately from validation loss."},{label:"Live demo boundary",detail:"The public CPU playground serves the small Shakespeare character model bb8-char-small-v002. It does not serve the live portfolio co-pilot or demonstrate the Qwen LoRA pilot."}],
    evaluation:[{metric:"Character baseline validation",value:"PPL 5.40; token accuracy 49.9%",context:"v002, 112,320 parameters, character tokenizer and stride-1 windows. Do not compare these values directly with BPE/LoRA models or stricter non-overlapping windows.",source:"https://github.com/Skywalker1910/BB-8/blob/main/docs/training_results.md"},{metric:"Grounded LoRA content + citation",value:"16/72 answerable cases (22.2%)",context:"88-case pilot: 72 answerable plus 16 absent-fact cases. Adapter passed required abstention phrase checks on 16/16, but failed follow-up/injection checks and was not promoted.",source:"https://github.com/Skywalker1910/BB-8/blob/main/docs/grounded_results_v005.md"},{metric:"Grounded pilot validation perplexity",value:"1.0262",context:"Small repetitive synthetic validation set after three epochs. Low perplexity did not establish reliable grounded QA; the experiment remained below the 80% promotion gate.",source:"https://github.com/Skywalker1910/BB-8/blob/main/docs/grounded_results_v005.md"}],
    limitations:["Perplexity depends on tokenizer, stride and supervision; it is not directly comparable across these experiments.","Phrase/citation checks are automated proxies, not human-verified factual accuracy. The grounded adapter is not production-ready."],
    blurb:"An 11-experiment LLM engineering study from a 112K-parameter character model through Qwen LoRA and grounded retrieval.",
    description:"This separate LLM engineering study does not serve the live portfolio assistant. It builds a decoder-only GPT-style Transformer in PyTorch from first principles, then extends the work into Qwen2.5 LoRA fine-tuning and grounded retrieval with its own tokenizers, training and evaluation loops, decoding strategies, experiment tracking, and CPU Lambda deployment path.",
    highlights:["Implemented embeddings, causal multi-head attention, Pre-LN decoder blocks, and language-model heads from first principles","Ran 11 documented experiments from 112K parameters to Qwen2.5-0.5B LoRA fine-tuning","Built an 80-case, five-configuration chat suite that exposed a prompt-format mismatch and 29% training-example truncation","Used an 88-case grounded-QA benchmark and 80% promotion gate to reject a perplexity-1.03 model that passed only 22% of content and citation checks","Added dataset hashing, commit pinning, versioned configs, a model registry, Hugging Face artifacts, and AWS deployment"],
    tags:["Python","PyTorch","Transformers","NLP","LoRA","BPE","Hugging Face","AWS Lambda"],
    year:2026, status:"in-progress", featured:true, published:true, sortOrder:3,
    github:"https://github.com/Skywalker1910/BB-8", demo:"https://chat.adityamore.dev/", huggingface:"https://huggingface.co/Skywalker1910/BB8"
  },
  {
    id:"fifa-world-cup-2026", kind:"project", title:"FIFA World Cup 2026 Prediction Platform",
    technicalDetails:[{label:"Data & tournament logic",detail:"SQLite stores accounts, sessions, fixtures, predictions and audit history. Regional prediction records are scoped by server; group standings and knockout slots derive from finalized results rather than silently promoting unconfirmed projections."},{label:"Evaluation & agent comparison",detail:"Agent picks store team/score forecasts, reasoning, confidence, provider and model metadata for a result-aware prediction matrix. Winner correctness and exact-score scoring are separate; recorded confidence is not a calibrated probability."},{label:"Infrastructure",detail:"A dependency-free Node HTTP server serves the static frontend, authenticated APIs and command center. Railway persistent storage retains SQLite; optional football-data.org synchronization updates match context."}],
    limitations:["No aggregate out-of-sample agent accuracy or calibration benchmark has been verified for this portfolio.","The configured public URL returned Railway Not Found during the September 30 capture; no fake application preview is substituted."],
    blurb:"A live regional prediction platform with player accounts, public leaderboards, tournament views, and a private command center.",
    description:"Built a compact full-stack World Cup prediction system on a dependency-free Node HTTP server and SQLite. One deployment serves distinct US and India scoring experiences, authenticated players and AI agents, public profiles, fixture and bracket views, administrative operations, and optional score synchronization.",
    highlights:["Designed two regional scoring systems and role-scoped access from one SQLite-backed deployment","Implemented prediction locking, score forecasts, public picks, profiles, leaderboards, and tournament progression","Built a private command center for accounts, results, prediction records, settings, ledgers, and audit history","Added dedicated AI agent accounts with reasoning, confidence, provider, model, and accuracy metadata","Deployed the containerized service on Railway with persistent storage and production operations documentation"],
    tags:["JavaScript","Node.js","SQLite","Docker","Railway","AI Agents","API Integration"],
    year:2026, status:"in-progress", featured:true, published:true, sortOrder:4,
    github:"https://github.com/Skywalker1910/FIFA-World-Cup-2026", demo:"https://game.adityamore.dev"
  },
  {
    id:"fifa-ai-agents", kind:"project", title:"FIFA 2026 AI Prediction Agents",
    technicalDetails:[{label:"Agent pipeline",detail:"A Node worker authenticates through the restricted ai_agent role, reads eligible fixtures, requests structured OpenAI predictions and submits validated team IDs, score forecasts, rationale and confidence through the platform API."},{label:"Validation & scheduling",detail:"Schema and eligibility checks enforce match IDs, lock windows and score constraints. Scheduled GitHub Actions support dry-run, due-window and update-existing modes; transient-lock retries are distinct from model reasoning."},{label:"Evaluation telemetry",detail:"Provider/model identifiers, response IDs and token metadata accompany picks for later result-based analysis. Claude/Gemini adapter scaffolding is not equivalent to verified comparative model results."}],
    limitations:["No verified model win rate is reported. Confidence values require calibration before probabilistic interpretation.","The companion game URL was unavailable at capture time."],
    blurb:"Scheduled LLM agents authenticate as players, reason over eligible fixtures, and submit structured predictions to the live game.",
    description:"Built a companion Node service that reads live fixture context, validates eligibility, requests structured predictions from an OpenAI model, and submits picks with scores, rationale, confidence, and model metadata through the prediction platform's API. GitHub Actions can run the agent on a schedule, with dry-run controls and provider scaffolds for Claude and Gemini.",
    highlights:["Implemented API-based login, fixture retrieval, prediction submission, logout, and transient-lock retries","Enforced structured output, valid teams and match IDs, lock windows, and conservative score forecasts","Captured model, response ID, token usage, reasoning, confidence, and request metadata","Added dry-run, due-window, next-match, and update-existing execution modes","Automated scheduled runs with GitHub Actions and provider-specific adapters"],
    tags:["JavaScript","Node.js","OpenAI API","AI Agents","Structured Outputs","GitHub Actions"],
    year:2026, status:"in-progress", featured:false, published:true, sortOrder:5,
    github:"https://github.com/Skywalker1910/FIFA-World-Cup-2026-AI-Agents", demo:"https://game.adityamore.dev"
  },
  {
    id:"skynet-aqi", kind:"project", title:"Skynet — AQI Prediction System",
    technicalDetails:[{label:"Environmental data pipeline",detail:"NASA TEMPO satellite observations, OpenAQ ground readings and weather context are transformed toward cell-hour feature tables for an Atlanta AQI pilot. Spatial grids and time-aligned observations connect satellite and ground sources."},{label:"Forecasting implementation",detail:"The LightGBM training implementation predicts target_aqi_t1 with a chronological split holding out the final 14 days, L1/MAE validation, 31 leaves and early stopping. Saved model metadata records features and cutoff."}],
    limitations:["A reproducible numerical MAE result was not verified. Some generic pipeline/lag-generation files remain scaffolds; this portfolio does not describe them as completed forecasts.","Satellite coverage and missing ground measurements constrain validation; no production monitoring outcome is claimed."],
    blurb:"An AQI forecasting prototype combining satellite observations, ground measurements and weather context.",
    description:"Developed an environmental-data and machine-learning prototype for the 2025 NASA Space Apps Challenge. The implemented LightGBM training path uses chronological validation; remaining pipeline scaffolds and unverified forecast accuracy are documented explicitly.",
    highlights:["Integrated NASA TEMPO, OpenAQ, weather, and traffic APIs","Designed ingestion, preprocessing, and feature-engineering pipelines","Modeled temporal and spatial patterns that influence air quality"],
    tags:["Python","scikit-learn","pandas","NumPy","ML Pipeline","Air Quality"],
    year:2025, status:"completed", featured:false, published:true, sortOrder:6
  },
  {
    id:"llm-defense", kind:"project", title:"LLM Jailbreak Defense Evaluation",
    technicalDetails:[{label:"Black-box experiment design",detail:"A 13-category attack corpus combines public jailbreak material and custom variants. A modular runner sends prompts to commercial LLMs and records responses, category outcomes, timing and usage without access to model internals."},{label:"Measurement",detail:"Query-success and refusal analyses separate model behavior from timeouts and exceptions. Category-level breakdowns support comparisons without conflating transport failures with successful defenses."}],
    limitations:["No new aggregate attack-success rate is claimed here without a verified run and denominator. Refusal detection is an evaluation proxy, not a guarantee of security."],
    blurb:"A black-box evaluation framework for jailbreak attempts, refusal behavior, latency, token use, and model failure modes.",
    description:"Replicated and extended the MASTERKEY approach for a Clemson security research project. The modular pipeline executes a multi-category jailbreak dataset against commercial LLMs, calculates query success rates, and categorizes timeouts, exceptions, and model refusals without internal model access.",
    highlights:["Built a 13-category dataset from public jailbreak sources and custom augmentations","Automated prompt execution, result logging, query-success evaluation, and category-level analysis","Tracked latency, token usage, response refusals, exceptions, and timeout failure modes","Evaluated multiple OpenAI model families through a reproducible black-box workflow"],
    tags:["Python","LLM","AI Security","Adversarial ML","Evaluation","OpenAI API"],
    year:2025, status:"completed", featured:false, published:true, sortOrder:7,
    github:"https://github.com/Skywalker1910/Evaluating-Defense-Mechanisms-Jailbreak-LLMs"
  },
  {
    id:"deep-learning-coursework", kind:"project", title:"Deep Learning Coursework — CPSC 8430",
    technicalDetails:[{label:"Sequence & language models",detail:"Attention-based encoder-decoder video captioning is evaluated with BLEU. BERT-Base extractive QA on noisy Spoken-SQuAD transcripts uses overlapping document windows, mixed precision, gradient checkpointing and gradient accumulation."},{label:"Generative vision",detail:"DCGAN, WGAN and ACGAN studies compare adversarial objectives and conditional generation with FID and Inception Score. These are distinct assignment tasks, not one combined production model."}],
    evaluation:[{metric:"Spoken-SQuAD F1 / exact match",value:"63.5% / 40.1%",context:"Documented BERT assignment evaluation on noisy speech transcripts; not a general QA benchmark or deployment metric.",source:"https://github.com/Skywalker1910/CPSC-8430-Deep-Learning"}],
    limitations:["BLEU/FID/Inception Score methods are documented, but no unverified numeric values are added. Assignment-specific scores are not cross-task comparisons."],
    blurb:"A four-repository implementation series covering video captioning, spoken question answering, and generative adversarial networks.",
    description:"Completed a graduate deep-learning implementation series in PyTorch spanning attention-based Seq2Seq video captioning, BERT question answering over noisy speech transcripts, and DCGAN, WGAN, and ACGAN image-generation experiments.",
    highlights:["Built an encoder-decoder video-captioning model with attention and BLEU evaluation","Fine-tuned BERT-Base on Spoken-SQuAD with document stride, mixed precision, gradient checkpointing, and accumulation","Reached 63.5% F1 and 40.1% exact match on the Spoken-SQuAD assignment evaluation","Implemented DCGAN, WGAN, and ACGAN variants and compared generation quality with FID and Inception Score"],
    tags:["Python","PyTorch","Deep Learning","BERT","Transformers","GANs","Computer Vision","NLP"],
    year:2024, status:"completed", featured:false, published:true, sortOrder:8,
    github:"https://github.com/Skywalker1910/CPSC-8430-Deep-Learning"
  },
  { technicalDetails:[{"label":"Implementation","detail":"OpenCV noise reduction and edge preprocessing feed contour-based candidate plate detection, followed by Tesseract OCR for text extraction."}], limitations:["No verified detection mAP, OCR character-error rate or dataset-wide accuracy is reported; this is an implementation study."], id:"alpr", kind:"project", title:"Automatic License Plate Recognition (ALPR)", blurb:"Computer vision system for vehicle license plate detection and text extraction.", description:"Developed a license plate detection and text extraction system using OpenCV and Tesseract OCR.", highlights:["Built plate detection using OpenCV contour analysis","Integrated Tesseract OCR","Implemented noise reduction and edge detection"], tags:["OpenCV","Tesseract","Python","OCR"], year:2021, status:"completed", featured:false, published:true, sortOrder:9, github:"https://github.com/Skywalker1910/License-Plate-Detection" },
  { technicalDetails:[{"label":"Implementation","detail":"TensorFlow mask detection and OpenCV frame processing support live-video safety monitoring, distancing checks and alerts."}], limitations:["No verified detector accuracy, throughput or calibration benchmark is reported. Camera-based monitoring is not proof of medical safety."], id:"covid-safeguard", kind:"project", title:"COVID-19 Safeguard System", blurb:"Real-time monitoring system using computer vision for safety compliance.", description:"Built a TensorFlow and OpenCV system for face-mask and social-distancing compliance from live video.", highlights:["Built face-mask detection using TensorFlow","Implemented distancing violation detection","Processes live video with alerts"], tags:["Computer Vision","TensorFlow","OpenCV"], year:2021, status:"completed", featured:false, published:true, sortOrder:10, github:"https://github.com/Skywalker1910/Covid-19-Safeguard" },
  { technicalDetails:[{"label":"Implementation","detail":"Python/Pygame event handling, player controls, enemy-wave updates, game state and score tracking form a 2D arcade game loop."}], limitations:["This is a software-engineering learning project, not an ML system; no model evaluation applies."], id:"alien-invasion", kind:"project", title:"Alien Invasion", blurb:"2D arcade-style game built while learning Python fundamentals.", description:"A Pygame space shooter with player controls, enemy waves, score tracking, and game-state management.", highlights:["Classic space shooter mechanics","Player controls and enemy waves","Score and game-state management"], tags:["Python","Pygame"], year:2020, status:"completed", featured:false, published:true, sortOrder:11 },
];

export const DEFAULT_EXPERIENCE: ExperienceContent[] = [
  { id:"clemson-volunteer-researcher", kind:"experience", title:"Researcher - LLM Agents and Human Behavior", organization:"Clemson University", department:"LLM Agents & Human Behavior", subdepartment:"School of Computing", location:"Clemson, SC / Remote", period:"Apr 2026 – Present", type:"Research", summary:"Researching whether societies of Large Language Model agents can realistically simulate human behavior and support early-stage behavioral studies under Dr. Long Cheng.", researchAreas:"Large Language Models · LLM Agents · Multi-Agent Systems · Generative AI · Human Behavior Simulation · AI Evaluation", bulletHeading:"Research & Contributions", tagHeading:"Technologies & Research Tools", bullets:["Researching whether societies of LLM agents can substitute for human participants in behavioral pilot studies.","Reproducing published behavioral experiments and designing new studies with AgentSociety, YuLan-OneSim, Generative Agents, and related multi-agent frameworks.","Developing a taxonomy and metrics for behavioral realism, consistency, and human alignment across decision-making and social scenarios.","Designing Trust Game and Dictator Game experiments to compare LLM-agent decisions with established human data.","Exploring benchmarks for behavioral realism, consistency, and human-agent similarity."], tags:["Python","Large Language Models","Multi-Agent Systems","AgentSociety","YuLan-OneSim","Generative Agents","MiroFish","Literature Review","Experimental Design","Behavioral Evaluation"], logo:"/soc-logo.png", accent:"orange", showOnTimeline:true, published:true, sortOrder:0 },
  { id:"clemson-graduate-hourly", kind:"experience", title:"Graduate Teaching Assistant", organization:"Clemson University", department:"Applied Data Science", subdepartment:"School of Computing", location:"Clemson, SC, USA", period:"Aug 2024 – Dec 2025", type:"Teaching", bullets:["Designed Jupyter labs and assignments covering data preprocessing, supervised learning, unsupervised learning, model evaluation, and visualization","Built automated grading pipelines with Python and nbgrader to improve scoring consistency and reduce manual effort","Maintained live course infrastructure and resolved notebook and autograder issues","Explained machine-learning concepts and debugged student code during office hours","Collaborated with faculty on curriculum design and Coursera deployment"], tags:["Python","Jupyter","nbgrader","scikit-learn","Pandas","NumPy"], logo:"/soc-logo.png", accent:"violet", showOnTimeline:true, published:true, sortOrder:1 },
  { id:"amdocs-test-engineer", kind:"experience", title:"Software Test Engineer", organization:"Amdocs", department:"Software Quality Engineering", subdepartment:"Telecom Systems", location:"Pune, India", period:"Oct 2021 – Dec 2022", type:"Software Engineering & QA", bullets:["Performed end-to-end, regression, and integration testing for enterprise telecom systems supporting AT&T","Designed test cases and validation strategies for new features from product requirements and stakeholder input","Ran functional, UI, and API release tests with Selenium and Postman","Triaged defects and collaborated with cross-functional Agile teams in the United States and India","Participated in requirements analysis and production-release validation"], tags:["Postman","Selenium","API Testing","Agile"], logo:"/amdocs-logo.png", accent:"teal", showOnTimeline:true, published:true, sortOrder:2 },
];

export function defaultsFor(kind: "projects" | "experience") {
  return kind === "projects" ? DEFAULT_PROJECTS : DEFAULT_EXPERIENCE;
}
