import type { ExperienceContent, ProjectContent } from "./types";

export const DEFAULT_PROJECTS: ProjectContent[] = [
  { id:"bb8-rag", kind:"project", title:"AI-Powered Portfolio Assistant (RAG-based System)", blurb:"BB-8 retrieves verified portfolio knowledge, grounds OpenAI responses, and links every answer back to relevant pages.", description:"Built BB-8, an AI portfolio co-pilot with a Retrieval-Augmented Generation pipeline over structured, verified portfolio data. The system creates OpenAI embeddings, stores and queries them with Amazon S3 Vectors, injects only relevant chunks into the Responses API, and displays source-page links in a persistent chat overlay.", highlights:["Designed section-aware chunking over a verified structured knowledge corpus","Implemented OpenAI embedding generation and Amazon S3 Vectors semantic search","Grounded Responses API prompts with only the top matching portfolio chunks","Added source-page links, persistent overlay navigation, and graceful local fallback","Created a retrieval evaluation suite for quality and latency measurement"], tags:["LLM","RAG","OpenAI API","Embeddings","Amazon S3 Vectors","Next.js","TypeScript","React"], year:2025, status:"in-progress", featured:true, published:true, sortOrder:0 },
  { id:"movie-recommendation", kind:"project", title:"Personalized Movie Recommendation System", blurb:"End-to-end recommendation engine using collaborative filtering, matrix factorization, and neural methods.", description:"Built an end-to-end recommendation system using MovieLens, TMDB, and IMDb datasets with collaborative filtering, content-based models, matrix factorization, and neural methods. Processed 26M+ ratings across 270K users and 45K movies.", highlights:["Processed 26M+ ratings across 270K users and 45K movies","Implemented FunkSVD achieving about 21% improvement over baseline","Designed ETL pipelines for multi-source data integration","Optimized sparse matrix computations for scalability"], tags:["Python","scikit-learn","PyTorch","Flask","PostgreSQL","Docker","Recommender Systems"], year:2024, status:"completed", featured:true, published:true, sortOrder:1 },
  { id:"skynet-aqi", kind:"project", title:"Skynet – AQI Prediction System", blurb:"ML pipeline to forecast Air Quality Index using NASA TEMPO, OpenAQ, weather, and traffic data.", description:"Built an end-to-end ML pipeline to forecast Air Quality Index using NASA TEMPO, OpenAQ, weather, and traffic APIs.", highlights:["Integrated NASA TEMPO, OpenAQ, weather, and traffic APIs","Designed data ingestion and preprocessing pipelines","Engineered environmental and traffic features","Modeled temporal and spatial AQI patterns"], tags:["Python","scikit-learn","pandas","NumPy","ML Pipeline","Air Quality"], year:2025, status:"completed", featured:true, published:true, sortOrder:2 },
  { id:"r2d2-transformer", kind:"project", title:"R2D2 – Experimental Transformer-based LLM", blurb:"Building transformer architectures from scratch to understand LLM internals and training dynamics.", description:"Experimental project focused on building transformer architectures from scratch, including tokenization, embeddings, attention mechanisms, and small-scale model training.", highlights:["Implementing tokenization, embeddings, and attention mechanisms","Training small-scale transformer models","Exploring LLM behavior and optimization","Understanding transformer internals from first principles"], tags:["Python","PyTorch","Transformers","NLP"], year:2025, status:"in-progress", featured:true, published:true, sortOrder:3 },
  { id:"neurallog", kind:"project", title:"NeuralLog – Intelligent Activity Tracking System", blurb:"Personal ML system to track daily activities, analyze behavior patterns, and generate insights.", description:"Personal ML system that tracks tasks, routines, and habits and applies ML models for behavioral analysis and personalized productivity insights.", highlights:["Tracks tasks, routines, and habits","Applies ML models for behavioral pattern analysis","Generates personalized productivity insights"], tags:["Python","Machine Learning","Data Analysis"], year:2025, status:"completed", featured:true, published:true, sortOrder:4 },
  { id:"alpr", kind:"project", title:"Automatic License Plate Recognition (ALPR)", blurb:"Computer vision system for vehicle license plate detection and text extraction.", description:"Developed a license plate detection and text extraction system using OpenCV and Tesseract OCR.", highlights:["Built plate detection using OpenCV contour analysis","Integrated Tesseract OCR","Implemented noise reduction and edge detection"], tags:["OpenCV","Tesseract","Python","OCR"], year:2021, status:"completed", featured:false, published:true, sortOrder:5, github:"https://github.com/Skywalker1910/License-Plate-Detection" },
  { id:"covid-safeguard", kind:"project", title:"COVID-19 Safeguard System", blurb:"Real-time monitoring system using computer vision for safety compliance.", description:"Built a TensorFlow and OpenCV system for face-mask and social-distancing compliance from live video.", highlights:["Built face-mask detection using TensorFlow","Implemented distancing violation detection","Processes live video with alerts"], tags:["Computer Vision","TensorFlow","OpenCV"], year:2021, status:"completed", featured:false, published:true, sortOrder:6, github:"https://github.com/Skywalker1910/Covid-19-Safeguard" },
  { id:"alien-invasion", kind:"project", title:"Alien Invasion", blurb:"2D arcade-style game built while learning Python fundamentals.", description:"A Pygame space shooter with player controls, enemy waves, score tracking, and game-state management.", highlights:["Classic space shooter mechanics","Player controls and enemy waves","Score and game-state management"], tags:["Python","Pygame"], year:2020, status:"completed", featured:false, published:true, sortOrder:7 },
];

export const DEFAULT_EXPERIENCE: ExperienceContent[] = [
  { id:"clemson-volunteer-researcher", kind:"experience", title:"Researcher - LLM Agents and Human Behavior", organization:"Clemson University", department:"LLM Agents & Human Behavior", subdepartment:"School of Computing", location:"Clemson, SC / Remote", period:"May 2026 – Present", type:"Volunteer Research", summary:"Conducting research under Dr. Long Cheng investigating whether Large Language Model agents can realistically simulate human behavior and how their behavioral fidelity can be systematically evaluated.", researchAreas:"Large Language Models · LLM Agents · Multi-Agent Systems · Generative AI · Human Behavior Simulation · AI Evaluation", bulletHeading:"Research & Contributions", tagHeading:"Technologies & Research Tools", bullets:["Conducting a comprehensive literature review of LLM-based human behavior simulation, autonomous agents, multi-agent systems, and AI-generated synthetic populations.","Investigating AgentSociety, YuLan-OneSim, Generative Agents, and MiroFish for large-scale simulation.","Developing a taxonomy of human behavior across decision-making, social interaction, cooperation, and trust.","Designing Trust Game and Dictator Game experiments to compare LLM-agent decisions with human data.","Exploring benchmarks for behavioral realism, consistency, and human-agent similarity."], tags:["Python","Large Language Models","Multi-Agent Systems","AgentSociety","YuLan-OneSim","Generative Agents","MiroFish","Literature Review","Experimental Design","Behavioral Evaluation"], logo:"/soc-logo.png", accent:"orange", showOnTimeline:true, published:true, sortOrder:0 },
  { id:"clemson-graduate-hourly", kind:"experience", title:"Graduate Student Hourly", organization:"Clemson University", department:"Data Science", subdepartment:"School of Computing", location:"Clemson, SC, USA", period:"Aug 2024 – Dec 2025", type:"Research & Teaching", bullets:["Designed Jupyter Notebook-based labs and assignments for a graduate Applied Data Science course","Built automated grading pipelines using nbgrader","Developed exercises covering preprocessing, outlier detection, model selection, cross-validation, feature selection, and PCA","Supported students through weekly office hours","Collaborated with faculty on curriculum design and Coursera deployment"], tags:["Python","Jupyter","scikit-learn","Pandas","NumPy"], logo:"/soc-logo.png", accent:"violet", showOnTimeline:true, published:true, sortOrder:1 },
  { id:"amdocs-test-engineer", kind:"experience", title:"Software Engineer", organization:"Amdocs", department:"Software Engineering & QA", subdepartment:"Telecom Systems", location:"Pune, India", period:"Oct 2021 – Dec 2022", type:"Software Engineering", bullets:["Performed end-to-end, regression, and API testing for enterprise telecom systems serving AT&T","Designed test cases and validation strategies for new releases","Automated workflows using Postman and proprietary tools","Collaborated with cross-functional global Agile teams","Participated in planning, requirements analysis, and production validation"], tags:["Postman","Selenium"], logo:"/amdocs-logo.png", accent:"teal", showOnTimeline:true, published:true, sortOrder:2 },
];

export function defaultsFor(kind: "projects" | "experience") {
  return kind === "projects" ? DEFAULT_PROJECTS : DEFAULT_EXPERIENCE;
}
