"use client";

import { motion, type Easing } from "framer-motion";
import Link from "next/link";
import { Bot, Clock3, Cookie, Database, EyeOff, FilePenLine, LockKeyhole, Mail, Server, ShieldCheck } from "lucide-react";

const fadeUp = (delay=0)=>({initial:{opacity:0,y:20},whileInView:{opacity:1,y:0},viewport:{once:true},transition:{duration:0.5,ease:"easeOut" as Easing,delay}});

const dataCategories = [
  { icon:EyeOff, title:"Anonymous page activity", accent:"text-sky-500", description:"When the operations table is enabled, the primary site records the public path visited, calendar date, total view count, and an anonymous random identifier for per-tab, per-path daily deduplication. It does not store your IP address, user agent, referrer, location, keystrokes, form values, or chat text as analytics data." },
  { icon:Mail, title:"Contact submissions", accent:"text-orange-500", description:"If you choose to send the contact form, the submitted first name, last name, email address, message, submission time, read state, and an optional owner-assigned sender category are stored in AWS DynamoDB so Aditya can review and respond." },
  { icon:Bot, title:"BB-8 conversations", accent:"text-violet-500", description:"When you use OpenAI mode, the latest short conversation window and relevant portfolio context are sent through this site’s server to OpenAI to generate a response. The application requests store: false and does not persist chat transcripts in its database. Your visible transcript is kept in this tab’s session storage." },
  { icon:Server, title:"Standard service processing", accent:"text-emerald-500", description:"AWS Amplify and ordinary internet infrastructure may process request metadata such as IP addresses as necessary to deliver, secure, and operate the site. The application uses an IP value only in volatile memory for chat/login rate limiting and does not write it to the portfolio databases." },
];

export default function PrivacyPage(){return <div className="container-max mx-auto max-w-4xl py-12 md:py-20">
  <motion.header {...fadeUp()} className="mb-14"><p className="mb-3 text-[11px] font-bold uppercase tracking-[0.3em] text-orange-500">Transparency & data</p><h1 className="text-4xl font-bold text-[var(--text)] md:text-5xl">Privacy Policy</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-[var(--muted)]">This policy explains the information the portfolio currently processes, why it is needed, where it is stored, and the choices available to visitors.</p><p className="mt-3 text-xs text-[var(--sub-muted)]">Effective and last updated: August 14, 2026</p></motion.header>

  <motion.section {...fadeUp(0.05)} className="mb-14"><div className="rounded-[1.5rem] border border-emerald-500/25 bg-emerald-500/10 p-6"><div className="flex gap-4"><ShieldCheck size={20} className="mt-0.5 shrink-0 text-emerald-500"/><div><h2 className="font-semibold text-[var(--text)]">Privacy summary</h2><p className="mt-2 text-sm leading-relaxed text-[var(--muted)]">There is no advertising, cross-site tracking, visitor geolocation, fingerprinting, or third-party analytics SDK. When enabled, anonymous path counters help the owner understand which portfolio sections are useful. Personal information is collected only when you submit the contact form or include it in a BB-8 prompt.</p></div></div></div></motion.section>

  <motion.section {...fadeUp(0.08)} className="mb-14" aria-labelledby="collected-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="collected-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">What is processed</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="grid gap-4 md:grid-cols-2">{dataCategories.map(({icon:Icon,title,accent,description},index)=><motion.article key={title} {...fadeUp(0.08+index*0.04)} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--border)] bg-[var(--tag-bg)]"><Icon size={17} className={accent}/></div><h3 className="mt-4 text-sm font-semibold text-[var(--text)]">{title}</h3><p className="mt-2 text-xs leading-relaxed text-[var(--muted)]">{description}</p></motion.article>)}</div></motion.section>

  <motion.section {...fadeUp(0.12)} className="mb-14" aria-labelledby="storage-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="storage-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Storage & retention</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="space-y-4 text-sm leading-relaxed text-[var(--muted)]">
    <div className="flex gap-3"><Clock3 size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Analytics:</strong> daily counters and anonymous deduplication records are stored in the portfolio DynamoDB table and configured to expire after approximately 400 days using DynamoDB TTL.</p></div>
    <div className="flex gap-3"><Database size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Contact messages:</strong> retained in the private contacts table until the owner deletes them or they are no longer reasonably needed for communication.</p></div>
    <div className="flex gap-3"><Cookie size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Browser storage:</strong> `sessionStorage` keeps the BB-8 transcript, chat state, anonymous analytics identifier, visited-path markers, and temporary contact drafts for the current browsing session.</p></div>
    <div className="flex gap-3"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Cookies:</strong> public visitors do not receive an advertising or analytics cookie. A signed, essential admin-session cookie is used only when the private site owner signs into the Command Center.</p></div>
  </div></motion.section>

  <motion.section {...fadeUp(0.16)} className="mb-14" aria-labelledby="sharing-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="sharing-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Service providers & use</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 text-sm leading-relaxed text-[var(--muted)]"><p>Information is used only to operate the portfolio, answer BB-8 questions, respond to contact submissions, secure the application, maintain live content, and understand aggregate page interest.</p><ul className="mt-4 space-y-2 text-xs"><li><strong className="text-[var(--text)]">AWS</strong> provides hosting, request processing, DynamoDB storage, and vector retrieval.</li><li><strong className="text-[var(--text)]">OpenAI</strong> processes BB-8 prompts and portfolio context when OpenAI chat or embedding features are used.</li><li><strong className="text-[var(--text)]">GitHub</strong> provides public profile and repository information requested by the server-side GitHub proxy.</li></ul><p className="mt-4">Data is not sold, rented, used for advertising, or intentionally shared for unrelated commercial purposes. Avoid including sensitive personal information in chat or the contact form.</p></div></motion.section>

  <motion.section {...fadeUp(0.2)} className="mb-14" aria-labelledby="choices-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="choices-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Your choices</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="space-y-4 text-sm leading-relaxed text-[var(--muted)]"><div className="flex gap-3"><EyeOff size={16} className="mt-0.5 shrink-0 text-orange-500"/><p>You can browse without using BB-8 or submitting the contact form. Closing the tab ends the browser session and clears session-scoped storage according to your browser&apos;s behavior.</p></div><div className="flex gap-3"><FilePenLine size={16} className="mt-0.5 shrink-0 text-orange-500"/><p>You may ask what contact information is held about you and request correction or deletion by emailing <a href="mailto:aditya.more@outlook.in" className="font-semibold text-[var(--text)] underline decoration-orange-500/50 underline-offset-4">aditya.more@outlook.in</a>. Anonymous analytics records cannot generally be linked back to a named individual.</p></div></div></motion.section>

  <motion.footer {...fadeUp(0.22)} className="flex flex-col gap-3 border-t border-[var(--border)] pt-8 text-xs text-[var(--sub-muted)] sm:flex-row sm:items-center sm:justify-between"><span>This policy will be updated when data practices materially change.</span><Link href="/notice" className="font-medium text-[var(--muted)] transition hover:text-[var(--text)]">Read the product notice →</Link></motion.footer>
</div>}
