"use client";

import { motion, type Easing } from "framer-motion";
import Link from "next/link";
import { Bot, Clock3, Cookie, Database, EyeOff, FilePenLine, LockKeyhole, Mail, Server, ShieldCheck } from "lucide-react";

const fadeUp = (delay=0)=>({initial:{opacity:0,y:20},whileInView:{opacity:1,y:0},viewport:{once:true},transition:{duration:0.5,ease:"easeOut" as Easing,delay}});

const dataCategories = [
  { icon:Server, title:"Mandatory anonymous reach", accent:"text-emerald-500", description:"For every public visit, I assign random, opaque visitor and session identifiers and record a server timestamp plus IP-derived country, country code, region/state, and region code when available. These identifiers contain no personal information and are unrelated to an IP address, email, name, device fingerprint, or location. City and more precise location are ignored and never persisted." },
  { icon:EyeOff, title:"Optional Basic Analytics", accent:"text-sky-500", description:"Only after you select Basic or Enhanced Analytics, I record page views, measured engagement duration, controlled feature events, and coarse device, operating-system, browser, and viewport categories. Basic Analytics does not recognize your browser across separate sessions." },
  { icon:Database, title:"Optional Enhanced Analytics", accent:"text-indigo-500", description:"Only after you explicitly select Enhanced Analytics, a random persistent browser identifier supports return-visit counts and page journeys. I also record a controlled traffic-source category and sanitized referring hostname. I may manually classify a pseudonymous journey; location and behavior never assign a category automatically." },
  { icon:Mail, title:"Contact submissions", accent:"text-orange-500", description:"If you submit the contact form, I store the name, email, message, submission time, read state, and an optional category in a separate AWS DynamoDB table. Only when Enhanced Analytics is active may the message include a one-way hashed analytics reference. I do not put an analytics identifier in the message or use it to create an expanded personal profile." },
  { icon:Bot, title:"BB-8 conversations and telemetry", accent:"text-violet-500", description:"When you use BB-8, a short conversation window and relevant portfolio context are sent through my server to OpenAI to generate a response. Requests use store: false, and I do not persist prompts or responses as analytics. With Basic or Enhanced consent, purpose-limited telemetry records anonymous opens, sessions, request outcome, latency, model, token totals, retrieval status, and coarse device/region context. Detailed agent actions require Enhanced consent." },
  { icon:Server, title:"Standard service processing", accent:"text-emerald-500", description:"AWS Amplify and ordinary internet infrastructure may temporarily process an IP address to deliver and secure the site and derive country/region headers. Request handlers convert it to a short-lived one-way key for in-memory rate limiting. My application never writes the raw address or rate-limit key to its databases and never uses either as visitor identity." },
];

export default function PrivacyPage(){return <div className="container-max mx-auto max-w-4xl py-12 md:py-20">
  <motion.header {...fadeUp()} className="mb-14"><p className="mb-3 text-[11px] font-bold uppercase tracking-[0.3em] text-orange-500">Transparency & data</p><h1 className="text-4xl font-bold text-[var(--text)] md:text-5xl">Privacy Policy</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-[var(--muted)]">This policy explains the information I currently process through this portfolio, why I need it, where it is stored, and the choices available to visitors.</p><p className="mt-3 text-xs text-[var(--sub-muted)]">Effective and last updated: August 20, 2026</p></motion.header>

  <motion.section {...fadeUp(0.05)} className="mb-14"><div className="rounded-[1.5rem] border border-emerald-500/25 bg-emerald-500/10 p-6"><div className="flex gap-4"><ShieldCheck size={20} className="mt-0.5 shrink-0 text-emerald-500"/><div><h2 className="font-semibold text-[var(--text)]">Privacy summary</h2><p className="mt-2 text-sm leading-relaxed text-[var(--muted)]">Mandatory anonymous visitor/session identity and country/region measurement apply to every public visit. Raw IP addresses, city, county, postal code, coordinates, and fingerprints are never written to my application databases. Page/device analytics, BB-8 telemetry, and returning-browser journeys are optional. There is no advertising, cross-site tracking, or third-party analytics SDK, and every public feature remains available when optional analytics is declined.</p></div></div></div></motion.section>

  <motion.section {...fadeUp(0.08)} className="mb-14" aria-labelledby="collected-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="collected-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">What is processed</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="grid gap-4 md:grid-cols-2">{dataCategories.map(({icon:Icon,title,accent,description},index)=><motion.article key={title} {...fadeUp(0.08+index*0.04)} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--border)] bg-[var(--tag-bg)]"><Icon size={17} className={accent}/></div><h3 className="mt-4 text-sm font-semibold text-[var(--text)]">{title}</h3><p className="mt-2 text-xs leading-relaxed text-[var(--muted)]">{description}</p></motion.article>)}</div></motion.section>

  <motion.section {...fadeUp(0.12)} className="mb-14" aria-labelledby="storage-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="storage-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Storage & retention</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="space-y-4 text-sm leading-relaxed text-[var(--muted)]">
    <div className="flex gap-3"><Clock3 size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Retention:</strong> mandatory telemetry targets 90 days, Basic and Enhanced Analytics 180 days, BB-8 telemetry 90 days, and contact submissions 365 days. These periods are configurable. DynamoDB TTL deletes eligible records asynchronously, so removal may occur after the eligibility time.</p></div>
    <div className="flex gap-3"><Database size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Server-side separation:</strong> analytics events, Enhanced visitor journeys, BB-8 telemetry, and contact messages use separate record families; contacts use a separate table. My server is the authoritative analytics store.</p></div>
    <div className="flex gap-3"><Cookie size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Browser storage:</strong> localStorage remembers your consent choice and version. Only Enhanced Analytics stores a random persistent visitor identifier. sessionStorage holds the current anonymous visitor/session identity, optional Enhanced visit ID, BB-8 session state/transcript, and temporary contact drafts—not analytics histories.</p></div>
    <div className="flex gap-3"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Cookies:</strong> public analytics does not use cookies. A signed, essential admin-session cookie is used only when I sign into the private Command Center.</p></div>
  </div></motion.section>

  <motion.section {...fadeUp(0.16)} className="mb-14" aria-labelledby="sharing-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="sharing-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Service providers & use</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 text-sm leading-relaxed text-[var(--muted)]"><p>Mandatory geography measures reach. Optional analytics measures content usefulness and UX. Enhanced Analytics supports return-visit and journey analysis. Optional BB-8 telemetry measures adoption and reliability. I do not use this data for advertising, automated decisions, or identity discovery.</p><ul className="mt-4 space-y-2 text-xs"><li><strong className="text-[var(--text)]">AWS</strong> provides hosting, request processing, IP-derived country/region headers, DynamoDB storage, and vector retrieval.</li><li><strong className="text-[var(--text)]">OpenAI</strong> processes BB-8 prompts and portfolio context when chat or embedding features are used and provides aggregate organization usage/cost reporting to my private Command Center.</li><li><strong className="text-[var(--text)]">GitHub</strong> provides public profile and repository information requested by my server-side GitHub proxy.</li></ul><p className="mt-4">I never store raw IP addresses, city, county, postal code, coordinates, hardware models, advertising identifiers, fingerprints, keystrokes, form values, or chat prompt/response text as analytics. Data is not sold, rented, or shared for unrelated commercial purposes.</p></div></motion.section>

  <motion.section {...fadeUp(0.2)} className="mb-14" aria-labelledby="choices-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="choices-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Your choices</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="space-y-4 text-sm leading-relaxed text-[var(--muted)]"><div className="flex gap-3"><EyeOff size={16} className="mt-0.5 shrink-0 text-orange-500"/><p>Use <strong className="font-semibold text-[var(--text)]">Analytics choices</strong> in the footer at any time to select Enhanced, Basic, or mandatory-only measurement. Mandatory visitor/session identity and country/region measurement cannot be disabled within the site. Moving away from Enhanced removes its persistent identifier and stops future optional collection; prior records expire under the applicable retention policy. Do Not Track and Global Privacy Control disable both optional tiers automatically.</p></div><div className="flex gap-3"><FilePenLine size={16} className="mt-0.5 shrink-0 text-orange-500"/><p>You may ask what contact information I hold about you and request correction or deletion by emailing <a href="mailto:aditya.more@outlook.in" className="font-semibold text-[var(--text)] underline decoration-orange-500/50 underline-offset-4">aditya.more@outlook.in</a>. Analytics identifiers are random and pseudonymous; only an Enhanced-consented contact submission can contain the separate one-way hashed linkage.</p></div></div></motion.section>

  <motion.footer {...fadeUp(0.22)} className="flex flex-col gap-3 border-t border-[var(--border)] pt-8 text-xs text-[var(--sub-muted)] sm:flex-row sm:items-center sm:justify-between"><span>This policy will be updated when data practices materially change.</span><Link href="/notice" className="font-medium text-[var(--muted)] transition hover:text-[var(--text)]">Read the product notice →</Link></motion.footer>
</div>}
