"use client";

import { motion, type Easing } from "framer-motion";
import Link from "next/link";
import { Bot, Clock3, Cookie, Database, EyeOff, FilePenLine, LockKeyhole, Mail, Server, ShieldCheck } from "lucide-react";

const fadeUp = (delay=0)=>({initial:{opacity:0,y:20},whileInView:{opacity:1,y:0},viewport:{once:true},transition:{duration:0.5,ease:"easeOut" as Easing,delay}});

const dataCategories = [
  { icon:EyeOff, title:"Basic site measurement", accent:"text-sky-500", description:"Unless you opt out, the primary site records each public page, a server timestamp, measured engagement duration, coarse country/region, and broad device, operating-system, browser, and viewport categories. This cookieless tier does not create a persistent visitor profile or connect activity across separate visits." },
  { icon:Database, title:"Optional enhanced analytics", accent:"text-indigo-500", description:"If you select Allow enhanced, a random browser identifier supports numbered return visits and page sequences. The site also records a broad traffic-source category and referring hostname. The owner may manually label that pseudonymous profile as recruiter, hiring manager, technical peer, student, or general visitor; location and behavior never assign this automatically." },
  { icon:Mail, title:"Contact submissions", accent:"text-orange-500", description:"If you choose to send the contact form, the submitted first name, last name, email address, message, submission time, read state, and an optional owner-assigned sender category are stored in AWS DynamoDB so Aditya can review and respond." },
  { icon:Bot, title:"BB-8 conversations", accent:"text-violet-500", description:"When you use OpenAI mode, the latest short conversation window and relevant portfolio context are sent through this site’s server to OpenAI to generate a response. The application requests store: false and does not persist chat transcripts in its database. Your visible transcript is kept in this tab’s session storage." },
  { icon:Server, title:"Standard service processing", accent:"text-emerald-500", description:"AWS Amplify and ordinary internet infrastructure may process request metadata such as IP addresses as necessary to deliver, secure, and operate the site. The application uses an IP value only in volatile memory for chat/login rate limiting and does not write it to the portfolio databases." },
];

export default function PrivacyPage(){return <div className="container-max mx-auto max-w-4xl py-12 md:py-20">
  <motion.header {...fadeUp()} className="mb-14"><p className="mb-3 text-[11px] font-bold uppercase tracking-[0.3em] text-orange-500">Transparency & data</p><h1 className="text-4xl font-bold text-[var(--text)] md:text-5xl">Privacy Policy</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-[var(--muted)]">This policy explains the information the portfolio currently processes, why it is needed, where it is stored, and the choices available to visitors.</p><p className="mt-3 text-xs text-[var(--sub-muted)]">Effective and last updated: August 16, 2026</p></motion.header>

  <motion.section {...fadeUp(0.05)} className="mb-14"><div className="rounded-[1.5rem] border border-emerald-500/25 bg-emerald-500/10 p-6"><div className="flex gap-4"><ShieldCheck size={20} className="mt-0.5 shrink-0 text-emerald-500"/><div><h2 className="font-semibold text-[var(--text)]">Privacy summary</h2><p className="mt-2 text-sm leading-relaxed text-[var(--muted)]">Basic first-party audience and UX measurement is enabled by default without a persistent identity and can be disabled at any time. Returning-browser journeys require your affirmative choice. There is no advertising, cross-site tracking, precise geolocation, device fingerprinting, or third-party analytics SDK, and every public feature remains available when analytics is disabled.</p></div></div></div></motion.section>

  <motion.section {...fadeUp(0.08)} className="mb-14" aria-labelledby="collected-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="collected-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">What is processed</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="grid gap-4 md:grid-cols-2">{dataCategories.map(({icon:Icon,title,accent,description},index)=><motion.article key={title} {...fadeUp(0.08+index*0.04)} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--border)] bg-[var(--tag-bg)]"><Icon size={17} className={accent}/></div><h3 className="mt-4 text-sm font-semibold text-[var(--text)]">{title}</h3><p className="mt-2 text-xs leading-relaxed text-[var(--muted)]">{description}</p></motion.article>)}</div></motion.section>

  <motion.section {...fadeUp(0.12)} className="mb-14" aria-labelledby="storage-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="storage-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Storage & retention</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="space-y-4 text-sm leading-relaxed text-[var(--muted)]">
    <div className="flex gap-3"><Clock3 size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Analytics:</strong> basic measurement events, aggregate counters, and optional pseudonymous journey records are stored in the portfolio DynamoDB table and configured to expire after approximately 365 days using DynamoDB TTL.</p></div>
    <div className="flex gap-3"><Database size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Contact messages:</strong> retained in the private contacts table until the owner deletes them or they are no longer reasonably needed for communication.</p></div>
    <div className="flex gap-3"><Cookie size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Browser storage:</strong> `localStorage` remembers whether you selected enhanced, basic-only, or disabled analytics. Only enhanced analytics stores a random visitor identifier. `sessionStorage` keeps its current 30-minute-inactivity visit identifier, plus the BB-8 transcript, chat state, and temporary contact drafts.</p></div>
    <div className="flex gap-3"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-orange-500"/><p><strong className="font-semibold text-[var(--text)]">Cookies:</strong> public analytics does not use cookies. A signed, essential admin-session cookie is used only when the private site owner signs into the Command Center.</p></div>
  </div></motion.section>

  <motion.section {...fadeUp(0.16)} className="mb-14" aria-labelledby="sharing-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="sharing-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Service providers & use</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 text-sm leading-relaxed text-[var(--muted)]"><p>Basic analytics is used only to measure this site&apos;s audience, content usefulness, navigation, and device-specific UX. Enhanced analytics supports return-visit and journey analysis. Neither tier is used for advertising, automated decisions, or identity discovery.</p><ul className="mt-4 space-y-2 text-xs"><li><strong className="text-[var(--text)]">AWS</strong> provides hosting, request processing, coarse IP-derived country information, DynamoDB storage, and vector retrieval.</li><li><strong className="text-[var(--text)]">OpenAI</strong> processes BB-8 prompts and portfolio context when OpenAI chat or embedding features are used.</li><li><strong className="text-[var(--text)]">GitHub</strong> provides public profile and repository information requested by the server-side GitHub proxy.</li></ul><p className="mt-4">The application never stores raw IP addresses, exact coordinates, city, postal code, hardware model, advertising identifiers, keystrokes, form values, or chat text as analytics. Data is not sold, rented, or shared for unrelated commercial purposes.</p></div></motion.section>

  <motion.section {...fadeUp(0.2)} className="mb-14" aria-labelledby="choices-heading"><div className="mb-6 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--border)]"/><h2 id="choices-heading" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[var(--sub-muted)]">Your choices</h2><span className="h-px flex-1 bg-[var(--border)]"/></div><div className="space-y-4 text-sm leading-relaxed text-[var(--muted)]"><div className="flex gap-3"><EyeOff size={16} className="mt-0.5 shrink-0 text-orange-500"/><p>Use <strong className="font-semibold text-[var(--text)]">Analytics choices</strong> in the footer at any time to select enhanced analytics, basic measurement only, or disable all analytics. Disabling removes analytics identifiers from this browser and stops future measurement; previously stored records remain until their retention period expires. Do Not Track and Global Privacy Control disable both tiers automatically.</p></div><div className="flex gap-3"><FilePenLine size={16} className="mt-0.5 shrink-0 text-orange-500"/><p>You may ask what contact information is held about you and request correction or deletion by emailing <a href="mailto:aditya.more@outlook.in" className="font-semibold text-[var(--text)] underline decoration-orange-500/50 underline-offset-4">aditya.more@outlook.in</a>. Analytics identifiers are random and pseudonymous, so stored analytics generally cannot be connected to a named person.</p></div></div></motion.section>

  <motion.footer {...fadeUp(0.22)} className="flex flex-col gap-3 border-t border-[var(--border)] pt-8 text-xs text-[var(--sub-muted)] sm:flex-row sm:items-center sm:justify-between"><span>This policy will be updated when data practices materially change.</span><Link href="/notice" className="font-medium text-[var(--muted)] transition hover:text-[var(--text)]">Read the product notice →</Link></motion.footer>
</div>}
