"use client";
import { useEffect, useState } from "react";
import { BrainCircuit, CheckCircle2, Database, Loader2, RefreshCw, Save, TriangleAlert } from "lucide-react";

type RagData = { settings:{enabled:boolean;topK:number;maxDistance:number}; infrastructure:{connection:string;bucketConfigured:boolean;index:string;embeddingModel:string;dimensions:number;vectors:number|null}; lastSync?:{state?:string;completedAt?:string;chunks?:number;message?:string}|null };
export default function RagControlPage(){
 const [data,setData]=useState<RagData|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
 const load=async()=>{setLoading(true);const r=await fetch("/api/admin/rag");if(r.status===401)return location.assign("/admin/login");const b=await r.json();if(r.ok)setData(b);else setMessage(b.error);setLoading(false)};useEffect(()=>{void load()},[]);
 const save=async()=>{if(!data)return;setBusy("save");const r=await fetch("/api/admin/rag",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data.settings)});const b=await r.json();setMessage(r.ok?"Runtime retrieval settings saved.":b.error);setBusy("");if(r.ok)void load()};
 const reindex=async()=>{if(!confirm("Rebuild the vector index from the currently published portfolio content? This uses OpenAI embedding tokens."))return;setBusy("index");setMessage("Indexing current published content…");const r=await fetch("/api/admin/rag",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reindex"})});const b=await r.json();setMessage(r.ok?`Indexed ${b.chunks} chunks and removed ${b.removed} stale vectors.`:b.error);setBusy("");void load()};
 if(loading)return <div className="flex items-center gap-2 p-10 text-sm text-[var(--muted)]"><Loader2 size={16} className="animate-spin"/> Inspecting RAG infrastructure…</div>;
 return <div className="mx-auto max-w-5xl p-6 md:p-10"><div className="mb-8"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-orange-500">BB-8 intelligence</p><h1 className="mt-2 text-3xl font-semibold">RAG Control</h1><p className="mt-2 text-sm text-[var(--muted)]">Tune retrieval, inspect vector health, and deliberately sync published content.</p></div>{message&&<div className="mb-5 rounded-xl border border-orange-500/25 bg-orange-500/10 px-4 py-3 text-sm text-orange-600">{message}</div>}{data&&<div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex items-center gap-2"><BrainCircuit size={17} className="text-orange-500"/><h2 className="font-semibold">Runtime retrieval</h2></div><p className="mt-2 text-xs leading-relaxed text-[var(--muted)]">These values take effect without a deployment. BB-8 falls back to keyword retrieval if semantic search is disabled or unavailable.</p><div className="mt-6 space-y-5"><label className="flex items-center justify-between rounded-xl border border-[var(--border)] p-4"><span><span className="block text-sm font-medium">Semantic retrieval</span><span className="text-xs text-[var(--muted)]">Query Amazon S3 Vectors</span></span><input type="checkbox" checked={data.settings.enabled} onChange={e=>setData({...data,settings:{...data.settings,enabled:e.target.checked}})} className="h-5 w-5 accent-orange-500"/></label><label className="block text-xs font-medium">Top matching chunks: {data.settings.topK}<input type="range" min={1} max={10} value={data.settings.topK} onChange={e=>setData({...data,settings:{...data.settings,topK:Number(e.target.value)}})} className="mt-3 w-full accent-orange-500"/></label><label className="block text-xs font-medium">Maximum vector distance: {data.settings.maxDistance.toFixed(2)}<input type="range" min={0.1} max={1.5} step={0.05} value={data.settings.maxDistance} onChange={e=>setData({...data,settings:{...data.settings,maxDistance:Number(e.target.value)}})} className="mt-3 w-full accent-orange-500"/></label><button onClick={()=>void save()} disabled={Boolean(busy)} className="cta-primary flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold">{busy==="save"?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>} Save settings</button></div></section>
 <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex items-center gap-2"><Database size={17} className="text-orange-500"/><h2 className="font-semibold">Index status</h2></div><div className="mt-6 space-y-3 text-sm">{[["Connection",data.infrastructure.connection],["Vector index",data.infrastructure.index],["Indexed chunks",data.infrastructure.vectors ?? "Unavailable"],["Embedding model",data.infrastructure.embeddingModel],["Dimensions",data.infrastructure.dimensions]].map(([k,v])=><div key={String(k)} className="flex justify-between gap-4 border-b border-[var(--border)] pb-3"><span className="text-[var(--muted)]">{k}</span><span className="text-right font-medium">{String(v)}</span></div>)}</div><div className="mt-5 rounded-xl border border-[var(--border)] bg-[var(--bg)] p-4 text-xs">{data.lastSync?.state==="ready"?<CheckCircle2 size={15} className="mb-2 text-emerald-500"/>:<TriangleAlert size={15} className="mb-2 text-amber-500"/>}<p className="font-medium">Last sync: {data.lastSync?.state ?? "Not recorded"}</p><p className="mt-1 text-[var(--muted)]">{data.lastSync?.completedAt ? new Date(data.lastSync.completedAt).toLocaleString() : "Run an index sync after publishing content changes."}</p></div><button onClick={()=>void reindex()} disabled={Boolean(busy)||data.infrastructure.connection!=="connected"} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-semibold hover:border-orange-500/40 disabled:opacity-50">{busy==="index"?<Loader2 size={15} className="animate-spin"/>:<RefreshCw size={15}/>} Reindex published content</button><p className="mt-3 text-[10px] leading-relaxed text-[var(--sub-muted)]">Embedding model, dimensions, bucket, and index name are deployment settings because changing them requires a compatible vector index.</p></section></div>}</div>;
}
